# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - BH-Web-App-3

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Install EntityFrameworkCore Tools
        run: |
            dotnet new tool-manifest
            dotnet tool install dotnet-ef

      - name: Generate EF Core Migration Script
        run: dotnet ef migrations script --idempotent --no-build --configuration Release --output ./sql-script.sql --context DeploymentAppWithDb.Data.ProjectContext --project ./DeploymentAppWithDb/DeploymentAppWithDb.csproj		
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

      - name: Upload migration SQL script
        uses: actions/upload-artifact@v4
        with:
          name: ddl-updates
          path: ./sql-script.sql

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Download migration SQL script
        uses: actions/download-artifact@v4
        with:
          name: ddl-updates
          path: ./

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4A39A2B547844721AF839950C61ABB66 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C28F8F15349F4BFCA5781649481DD8D2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1197D8AF065449379DCBB1FF56D07994 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BH-Web-App-3'
          slot-name: 'Production'
          package: .

      - name: Azure SQL Deploy
        uses: Azure/sql-action@v2
        with:
          connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
          path: ./sql-script.sql
